### ISSUE TITLE
missing function?

### ISSUE THREAD

**Issue by ghost** [jjaner/genaudiolib#1]
I am interested in the supervised nmf separation, but I think a function is missing called apl_estimate_nmf.
Please provide this function. Thank you very much for your time and research!

**Comment by jjaner** [comment]
Thanks for pointing it out. There was a mistake in the function description (apl_estimate_nmf is actually the function alp_unsupervised_nmf). Hence you can use the function apl_unsupervised_nmf() and store a .mat file with the resulting matrix.
